data_dir <- getwd ()
nf <- length (list.files (data_dir, pattern = '.zip'))
if (nf < 6)
    bike_write_test_data (data_dir = data_dir)
bikedb <- file.path (getwd (), "testdb")
if (!file.exists (bikedb))
    store_bikedata (data_dir = data_dir, bikedb = bikedb)
