#pragma once

#include <stdio.h>
#include <string>
#include <vector>
#include <map>
#include <unordered_set>
#include <locale> // tolower
#include <algorithm> // count

#include <boost/algorithm/string/replace.hpp>


// Stores the header data structure for a given city and file type, as directly
// read in data from R/sysdata.rda, as generated by the data-raw/sysdata.Rmd
// script
struct HeaderStruct {
    unsigned int nvalues;
    bool data_has_stations, terminal_quote;
    std::vector <bool> quoted;
    std::vector <int> position_file2db;
};

// total number of fields in the trip table of database
const unsigned int num_db_fields = 15;
