// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_get_bikedata
int rcpp_get_bikedata();
RcppExport SEXP bikedata_rcpp_get_bikedata() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_get_bikedata());
    return rcpp_result_gen;
END_RCPP
}
// importDataToSpatialite
int importDataToSpatialite(CharacterVector datafiles, const char* spdb);
RcppExport SEXP bikedata_importDataToSpatialite(SEXP datafilesSEXP, SEXP spdbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type datafiles(datafilesSEXP);
    Rcpp::traits::input_parameter< const char* >::type spdb(spdbSEXP);
    rcpp_result_gen = Rcpp::wrap(importDataToSpatialite(datafiles, spdb));
    return rcpp_result_gen;
END_RCPP
}
