# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' create_station_table
#'
#' Creates and/or updates the table of stations in the database
#' 
#' @param dbcon Active connection to sqlite3 database
#' @param stationqry Station query constructed during reading of data with
#' importDataToSqlite3 ()
#'
#' @return integer result code
#'
#' @noRd
NULL

#' read_one_line_nyc
#'
#' @noRd
NULL

#' importDataToSqlite3
#'
#' Extracts bike data for NYC citibike
#' 
#' @param datafiles A character vector containin the paths to the citibike 
#' .csv files to import.
#' @param spdb A string containing the path to the Sqlite3 database to 
#' use. It will be created automatically.
#' @param quiet If FALSE, progress is displayed on screen
#'
#' @return integer result code
#'
#' @noRd
importDataToSqlite3 <- function(datafiles, spdb, quiet) {
    .Call('bikedata_importDataToSqlite3', PACKAGE = 'bikedata', datafiles, spdb, quiet)
}

#' create_sqlite3_db
#'
#' Initial creation of SQLite3 database
#' 
#' @param spdb A string containing the path to the Sqlite3 database to 
#' be created.
#'
#' @return integer result code
#'
#' @noRd
create_sqlite3_db <- function(spdb) {
    .Call('bikedata_create_sqlite3_db', PACKAGE = 'bikedata', spdb)
}

#' create_db_indexes
#'
#' Creates the specified indexes in the database to speed up queries. Note
#' that for the full dataset this may take some time.
#' 
#' @param spdb A string containing the path to the sqlite3 database to use.
#' @param tables A vector with the tables for which to create indexes. This
#' vector should be the same length as the cols vector.
#' @param cols A vector with the fields for which to create indexes.
#' @param reindex If false, indexes are created, otherwise they are simply
#' reindexed.
#'
#' @return integer result code
#'
#' @noRd
create_db_indexes <- function(spdb, tables, cols, reindex) {
    .Call('bikedata_create_db_indexes', PACKAGE = 'bikedata', spdb, tables, cols, reindex)
}

#' strtokm
#'
#' A string delimiter function based on strtok
#' Accessed from StackOverflow (using M Oehm):
#' http://stackoverflow.com/questions/29847915/implementing-strtok-whose-delimiter-has-more-than-one-character
#'
#' @noRd
NULL

#' compare_version_numbers
#'
#' Function to compare version numbers
#' First argument is compared to the second argument
#' Return value:
#' -1 = Argument one version lower than Argument two version
#' 0 = Argument one version equal to Argument two version
#' 1 = Argument one version higher than Argument two version
#'
#' @noRd
NULL

#' rm_dos_end
#'
#' Remove dos line ending from a character string
#'
#' @noRd
NULL

#' line_has_quotes
#'
#' Determine whether or not fields within a line are separated by double quotes
#' and a comma, or just comma separated.
#'
#' @param line Character string with or without double-quote-comma separation
#'
#' @return true if line is delimited by double quotes and commas, false if
#' commas only.
#'
#' @noRd
NULL

#' convert_datetime
#'
#' Datetime strings for NYC change between 08/2014 and 09/2014 from
#' yyyy-mm-dd HH:MM:SS to m/d/yyyy HH:MM:SS. sqlite3 can't combine dates in
#' different formats, so this converts the latter to former formats.
#'
#' @noRd
NULL

