# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_get_bikedata
#'
#' Extracts bike data for NYC citibike
#'
#' @return nothing
rcpp_get_bikedata <- function() {
    .Call('bikedata_rcpp_get_bikedata', PACKAGE = 'bikedata')
}

